name: Build golden-dawn workflow
run-name: Build golden-dawn
on: [push]
jobs:
  BuildAction:
    runs-on: ubuntu-latest
    steps:
      # Install rust toolchain.
      - name: Install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install cross
        run: cargo install cross

      - name: Checkout repository files
        uses: actions/checkout@v4

      - name: Build for Linux
        run: cross build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows
        run: cross build --release --target x86_64-pc-windows-gnu

      # Show all files.
      - name: Find exe files
        run: find ./