name: Build golden-dawn workflow
run-name: Build golden-dawn
on: [push]
jobs:
  BuildAction:
    runs-on: ubuntu-latest
    steps:
      # Install rust toolchain.
      - name: Install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install cross
        run: cargo install cross

      - name: Checkout repository files
        uses: actions/checkout@v4

      - name: Build for Linux
        run: cross build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows
        run: cross build --release --target x86_64-pc-windows-gnu

      - name: Test for Linux
        run: cross test --target x86_64-unknown-linux-gnu

      - name: Test for Windows
        run: cross test --target x86_64-pc-windows-gnu

      - name: Show all files
        run: find ./

      - name: Save the binary file for Linux
        uses: actions/upload-artifact@v4
        with:
          name: For Linux
          path: ./target/x86_64-unknown-linux-gnu/release/golden-dawn
          retention-days: 7

      - name: Save the binary file for Windows
        uses: actions/upload-artifact@v4
        with:
          name: For Windows
          path: ./target/x86_64-pc-windows-gnu/release/golden-dawn.exe 
          retention-days: 7